/// Generates `bin/src/version.g.dart` from `pubspec.yaml`.
///
/// ```bash
/// dart run tool/version/generate_version.dart          # write the file
/// dart run tool/version/generate_version.dart --check  # fail if stale (CI)
/// ```
library;

import 'dart:io';

const _pubspecPath = 'pubspec.yaml';
const _outputPath = 'bin/src/version.g.dart';

void main(List<String> args) {
  final check = args.contains('--check');
  final version = pubspecVersion();
  final content = _render(version);
  final file = File(_outputPath);

  if (check) {
    if (!file.existsSync() || file.readAsStringSync() != content) {
      stderr
        ..writeln('$_outputPath is out of date (pubspec version: $version).')
        ..writeln('Run `dart run tool/version/generate_version.dart`.');
      exitCode = 1;
      return;
    }
    stdout.writeln('CLI version file is in sync ($version).');
    return;
  }

  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('wrote $_outputPath ($version)');
}

/// Reads the top-level `version:` field from [pubspec.yaml].
String pubspecVersion() {
  final pubspec = File(_pubspecPath);
  if (!pubspec.existsSync()) {
    throw StateError('Missing $_pubspecPath');
  }
  for (final line in pubspec.readAsLinesSync()) {
    final match = RegExp(r'^version:\s*(\S+)\s*$').firstMatch(line);
    if (match != null) return match.group(1)!;
  }
  throw StateError('No top-level `version:` field in $_pubspecPath');
}

String _render(String version) {
  return '// GENERATED by `dart run tool/version/generate_version.dart` — do not edit.\n'
      '// Source of truth: the `version:` field in pubspec.yaml.\n'
      '// Verify in CI: `dart run tool/version/generate_version.dart --check`.\n'
      "const String pqthresholdCliVersion = '$version';\n";
}
